import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@/app/globals.css'

import { Provider } from '@/components/providers'
import { Toaster } from '@/components/ui/sonner'

export const font = Montserrat({
	subsets: ['latin'],
	weight: ['400', '600', '800']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={font.className}>
				<Provider>{children}</Provider>
				<Toaster position='top-center' richColors />
			</body>
		</html>
	)
}
